project:
  type: book

book:
  title: "Proteinlerin Moleküler Dinamik Simülasyonları"
  author: "Doç. Dr. Mustafa TEKPINAR"
  date: today
  chapters:
  - index.qmd
  - chapters/01-intro.qmd
  - chapters/02-md-preparations.qmd
  - chapters/03-md-analyses.qmd
  - chapters/references.qmd

format:
  html:
    theme: cosmo
  pdf:
    pdf-engine: xelatex
    documentclass: scrbook

output-dir: _book
