project:
  type: book

book:
  title: "Proteinlerin Moleküler Dinamik Simülasyonları"
  output-file: "Proteinlerin-Molekuler-Dinamik-Simulasyonlari"
  author: "Doç. Dr. Mustafa TEKPINAR"
  date: today
  language: tr-TR
  chapters:
  - index.qmd
  - chapters/01-intro.qmd
  - chapters/02-md-preparations.qmd
  - chapters/03-md-analyses.qmd
  - chapters/appendices/01-amino-acids-and-proteins.qmd
  - chapters/appendices/02-md-forcefields.qmd 
  - references.qmd

format:
  html:
    lang: tr
    theme: cerulean
  pdf:
    lang: tr
    pdf-engine: lualatex
    documentclass: scrbook

output-dir: _book
